spring.application.name=123Ovinos
spring.datasource.url=jdbc:mysql://localhost:3306/123Ovinos
spring.datasource.username=root
spring.datasource.password=Mcqueen095

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true